language: node_js
node_js:
  - "20"
install:
  - npm install
cache:
  directories:
    - node_modules
env:
  - CI=true
script:
  - npm run test
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: travis